default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: adm_facil_development
  username: anderson
  password: 13101994
  host: localhost
  port: 5432

production:
  <<: *default
  database: adm_facil_production
  username: anderson
  password: 13101994
  host: localhost
  port: 5432
